# Import of the main build_settings file
include:
  - ../../fastlane/build_settings.yml

# Definition of the project
name: CosmonautService
settings:
  groups:
    - BuildSettings

# Definition of the targets that exists within the project
targets:
  
  # The service framework containing implementations
  ISSCosmonautService:
    type: framework
    platform: iOS
    sources: CosmonautService
    dependencies:
      # Linking and implements the `ISSCosmonautServiceCore`  
      - framework: ISSCosmonautServiceCore.framework
        implicit: true
      # Linking the SpacesuitServiceCore in order to be able to use
      # the public interfaces from it.
      - framework: ISSSpacesuitServiceCore.framework
        implicit: true
      # Core layer
      - framework: ISSPersistence.framework
        implicit: true
      - framework: ISSNetwork.framework
        implicit: true
      - framework: ISSUIComponents.framework
        implicit: true
      - framework: ISSRadio.framework
        implicit: true
      - framework: ISSNetworkCore.framework
        implicit: true
  
  # Core Framework for ISSCosmonautService
  # defines interfaces and plain public types
  ISSCosmonautServiceCore:
    type: framework
    platform: iOS
    sources: CosmonautServiceCore
    dependencies:
      - framework: ISSNetworkCore.framework
        implicit: true
        
  # Tests for the main application
  CosmonautServiceTests:
    type: bundle.unit-test
    platform: iOS
    sources: CosmonautServiceTests
    dependencies:
      - target: ISSCosmonautService
