# Import of the main build_settings file
include:
  - ../../fastlane/build_settings.yml

# Definition of the project
name: Scaffold
settings:
  groups:
    - BuildSettings

# Definition of the targets that exists within the project
targets:
  
  # The main application
  ISSScaffold:
    type: framework
    platform: iOS
    sources: Scaffold
    dependencies:
      # Core
      - framework: ISSUIComponents.framework
        implicit: true
  
  # Tests for the main application
  ScaffoldTests:
    type: bundle.unit-test
    platform: iOS
    sources: ScaffoldTests
    dependencies:
      - target: ISSScaffold
