require_relative "../../fastlane/Podfile"

platform :ios, '13.0'
workspace 'CosmonautApp'

# Linking pods for desired frameworks
# Domain
spacesuit_sdk
cosmonaut_sdk
scaffold_sdk
# Service
spacesuitservice_sdk
cosmonautservice_sdk
# Core
network_sdk
radio_sdk
uicomponents_sdk
persistence_sdk


target 'CosmonautApp' do
  use_frameworks!
    
  pod $snapKit.name, $snapKit.version
  # Linking all dynamic libraries towards the main app target
  # as only app can copy frameworks
  add_linked_libs_from_sdks_to_app
  
  target 'CosmonautAppTests' do
    inherit! :search_paths
    
  end
  
  target 'CosmonautAppUITests' do
    # Pods for testing
  end

end
