# Import of the main build_settings file
include:
  - ../../fastlane/build_settings.yml

# Definition of the project
name: SpacesuitService
settings:
  groups:
    - BuildSettings

# Definition of the targets that exists within the project
targets:
  
  # The service framework containing implementations
  ISSSpacesuitService:
    type: framework
    platform: iOS
    sources: SpacesuitService
    dependencies:
    # Linking and implements the `ISSSpacesuitServiceCore` protocols  
    - framework: ISSSpacesuitServiceCore.framework
      implicit: true
    # Core layer dependencies
    - framework: ISSPersistence.framework
      implicit: true
    - framework: ISSNetwork.framework
      implicit: true
    - framework: ISSUIComponents.framework
      implicit: true
    - framework: ISSRadio.framework
      implicit: true
      
  # Core Framework for ISSSpacesuitServiceCore
  # defines interfaces and plain public types
  ISSSpacesuitServiceCore:
    type: framework
    platform: iOS
    sources: SpacesuitServiceCore
    dependencies:
      # Linking and uses only interfaces from the NetworkCore
      - framework: ISSNetworkCore.framework
        implicit: true
        
  # Tests for the main application
  SpacesuitServiceTests:
    type: bundle.unit-test
    platform: iOS
    sources: SpacesuitServiceTests
    dependencies:
      - target: ISSSpacesuitService
