require_relative "scripts/AppFactory/app_factory"

lane: make_new_app do |options|
  app_name = options[:app_name]
  destination_path = options[:destination_path]
  
  AppFactory.new app_name, destination_path
end